# Automatically created from setup.cfg
name: ebsdlab
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - scipy>=1.14
  - matplotlib
  # Development dependencies
  - sphinx
  - jupyter_sphinx
  - sphinx_tabs
  - piccolo-theme
  - pytest
  - pytest-mpl
  - isort
  - mypy
  - pylint
  - pre-commit
  - pip-tools
  - h5py
