# Automatically created from setup.cfg
name: ebsdlab
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pillow
  - numpy
  - scipy
  - matplotlib
  # Development dependencies
  - sphinx
  - jupyter_sphinx
  - sphinx_tabs
  - pytest
  - pytest-mpl
  - bump-my-version
  - isort
  - mypy
  - pylint
  - pre-commit
  - requests
  - pip-tools
